package provider

import (
	"context"
	"fmt"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &notificationPublisherResource{}
	_ resource.ResourceWithConfigure   = &notificationPublisherResource{}
	_ resource.ResourceWithImportState = &notificationPublisherResource{}
)

type (
	notificationPublisherResource struct {
		client *dtrack.Client
		semver *Semver
	}

	notificationPublisherResourceModel struct {
		ID               types.String `tfsdk:"id"`
		Name             types.String `tfsdk:"name"`
		Description      types.String `tfsdk:"description"`
		PublisherClass   types.String `tfsdk:"publisher_class"`
		Template         types.String `tfsdk:"template"`
		TemplateMIMEType types.String `tfsdk:"template_mime_type"`
		DefaultPublisher types.Bool   `tfsdk:"default_publisher"`
	}
)

func NewNotificationPublisherResource() resource.Resource {
	return &notificationPublisherResource{}
}

func (*notificationPublisherResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_publisher"
}

func (*notificationPublisherResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Notification Publisher.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "UUID for the Notification Publisher as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the Notification Publisher.",
				Required:    true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the Notification Publisher.",
				Optional:    true,
			},
			"publisher_class": schema.StringAttribute{
				Description: "Fully-qualified class name of the publisher implementation.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"template": schema.StringAttribute{
				Description: "Template content for the publisher.",
				Optional:    true,
			},
			"template_mime_type": schema.StringAttribute{
				Description: "MIME type of the template (e.g. 'application/json').",
				Required:    true,
			},
			"default_publisher": schema.BoolAttribute{
				Description: "Whether this is a default built-in publisher.",
				Computed:    true,
			},
		},
	}
}

func (r *notificationPublisherResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan notificationPublisherResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Creating Notification Publisher", map[string]any{
		"name": plan.Name.ValueString(),
	})

	publisher := dtrack.NotificationPublisher{
		Name:             plan.Name.ValueString(),
		PublisherClass:   plan.PublisherClass.ValueString(),
		TemplateMIMEType: plan.TemplateMIMEType.ValueString(),
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		publisher.Description = plan.Description.ValueString()
	}
	if !plan.Template.IsNull() && !plan.Template.IsUnknown() {
		publisher.Template = plan.Template.ValueString()
	}

	publisherRes, err := r.client.Notification.CreatePublisher(ctx, publisher)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating notification publisher",
			"Error from: "+err.Error(),
		)
		return
	}

	r.mapToState(&plan, publisherRes)

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Created Notification Publisher", map[string]any{
		"id":   plan.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
}

func (r *notificationPublisherResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state notificationPublisherResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisherID, diag := TryParseUUID(state.ID, LifecycleRead, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	tflog.Debug(ctx, "Reading Notification Publisher", map[string]any{
		"id": publisherID.String(),
	})

	publisher, err := r.findPublisher(ctx, publisherID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to read notification publisher",
			"Error from: "+err.Error(),
		)
		return
	}

	r.mapToState(&state, *publisher)

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Read Notification Publisher", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

func (r *notificationPublisherResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan notificationPublisherResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisherID, diag := TryParseUUID(plan.ID, LifecycleUpdate, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	updateReq := dtrack.NotificationPublisher{
		UUID:             publisherID,
		Name:             plan.Name.ValueString(),
		PublisherClass:   plan.PublisherClass.ValueString(),
		TemplateMIMEType: plan.TemplateMIMEType.ValueString(),
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		updateReq.Description = plan.Description.ValueString()
	}
	if !plan.Template.IsNull() && !plan.Template.IsUnknown() {
		updateReq.Template = plan.Template.ValueString()
	}

	tflog.Debug(ctx, "Updating Notification Publisher", map[string]any{
		"id":   publisherID.String(),
		"name": updateReq.Name,
	})

	publisherRes, err := r.client.Notification.UpdatePublisher(ctx, updateReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to update notification publisher",
			"Error from: "+err.Error(),
		)
		return
	}

	r.mapToState(&plan, publisherRes)

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Updated Notification Publisher", map[string]any{
		"id":   plan.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
}

func (r *notificationPublisherResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state notificationPublisherResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisherID, diag := TryParseUUID(state.ID, LifecycleDelete, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	tflog.Debug(ctx, "Deleting Notification Publisher", map[string]any{
		"id":   publisherID.String(),
		"name": state.Name.ValueString(),
	})

	err := r.client.Notification.DeletePublisher(ctx, publisherID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to delete notification publisher",
			"Error from: "+err.Error(),
		)
		return
	}
	tflog.Debug(ctx, "Deleted Notification Publisher", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

func (*notificationPublisherResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Importing Notification Publisher", map[string]any{
		"id": req.ID,
	})
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Imported Notification Publisher", map[string]any{
		"id": req.ID,
	})
}

func (r *notificationPublisherResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfoData, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfoData.client
	r.semver = clientInfoData.semver
}

func (r *notificationPublisherResource) findPublisher(ctx context.Context, publisherID uuid.UUID) (*dtrack.NotificationPublisher, error) {
	publishers, err := r.client.Notification.GetAllPublishers(ctx)
	if err != nil {
		return nil, err
	}

	return Find(publishers, func(pub dtrack.NotificationPublisher) bool {
		return pub.UUID == publisherID
	})
}

func (*notificationPublisherResource) mapToState(state *notificationPublisherResourceModel, publisher dtrack.NotificationPublisher) {
	state.ID = types.StringValue(publisher.UUID.String())
	state.Name = types.StringValue(publisher.Name)
	state.PublisherClass = types.StringValue(publisher.PublisherClass)
	state.TemplateMIMEType = types.StringValue(publisher.TemplateMIMEType)
	state.DefaultPublisher = types.BoolValue(publisher.DefaultPublisher)

	if publisher.Description != "" {
		state.Description = types.StringValue(publisher.Description)
	} else if !state.Description.IsNull() {
		state.Description = types.StringNull()
	}

	if publisher.Template != "" {
		state.Template = types.StringValue(publisher.Template)
	} else if !state.Template.IsNull() {
		state.Template = types.StringNull()
	}
}
