package provider

import (
	"context"
	"fmt"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &notificationRuleResource{}
	_ resource.ResourceWithConfigure   = &notificationRuleResource{}
	_ resource.ResourceWithImportState = &notificationRuleResource{}
)

type (
	notificationRuleResource struct {
		client *dtrack.Client
		semver *Semver
	}

	notificationRuleResourceModel struct {
		ID                    types.String `tfsdk:"id"`
		Name                  types.String `tfsdk:"name"`
		Enabled               types.Bool   `tfsdk:"enabled"`
		NotifyChildren        types.Bool   `tfsdk:"notify_children"`
		LogSuccessfulPublish  types.Bool   `tfsdk:"log_successful_publish"`
		Scope                 types.String `tfsdk:"scope"`
		NotificationLevel     types.String `tfsdk:"notification_level"`
		TriggerType           types.String `tfsdk:"trigger_type"`
		NotifyOn              types.Set    `tfsdk:"notify_on"`
		Message               types.String `tfsdk:"message"`
		PublisherID           types.String `tfsdk:"publisher_id"`
		PublisherConfig       types.String `tfsdk:"publisher_config"`
		ScheduleCron          types.String `tfsdk:"schedule_cron"`
		ScheduleSkipUnchanged types.Bool   `tfsdk:"schedule_skip_unchanged"`
	}
)

func NewNotificationRuleResource() resource.Resource {
	return &notificationRuleResource{}
}

func (*notificationRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_rule"
}

func (*notificationRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Notification Rule.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "UUID for the Notification Rule as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the Notification Rule.",
				Required:    true,
			},
			"enabled": schema.BoolAttribute{
				Description: "Whether the Notification Rule is enabled. Defaults to true.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"notify_children": schema.BoolAttribute{
				Description: "Whether to also notify for child projects. Defaults to true.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"log_successful_publish": schema.BoolAttribute{
				Description: "Whether to log successful notification publishes. Defaults to false.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
			"scope": schema.StringAttribute{
				Description: "Scope of the Notification Rule. Valid values are 'SYSTEM' and 'PORTFOLIO'.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"notification_level": schema.StringAttribute{
				Description: "Notification level threshold. Valid values are 'INFORMATIONAL', 'WARNING', 'ERROR'.",
				Optional:    true,
			},
			"trigger_type": schema.StringAttribute{
				Description: "Trigger type for the Notification Rule. Valid values are 'EVENT' and 'SCHEDULE'. Defaults to 'EVENT'.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("EVENT"),
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"notify_on": schema.SetAttribute{
				Description: "Set of notification group names to notify on. " +
					"For PORTFOLIO scope: NEW_VULNERABILITY, NEW_VULNERABLE_DEPENDENCY, PROJECT_AUDIT_CHANGE, " +
					"BOM_CONSUMED, BOM_PROCESSED, BOM_PROCESSING_FAILED, BOM_VALIDATION_FAILED, " +
					"VEX_CONSUMED, VEX_PROCESSED, POLICY_VIOLATION, PROJECT_CREATED, USER_CREATED, USER_DELETED. " +
					"For PORTFOLIO scheduled: NEW_VULNERABILITIES_SUMMARY, NEW_POLICY_VIOLATIONS_SUMMARY. " +
					"For SYSTEM scope: CONFIGURATION, DATASOURCE_MIRRORING, REPOSITORY, INTEGRATION, INDEXING_SERVICE, FILE_SYSTEM, ANALYZER.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"message": schema.StringAttribute{
				Description: "Custom message for the notification. Maximum 1024 characters.",
				Optional:    true,
			},
			"publisher_id": schema.StringAttribute{
				Description: "UUID for the Notification Publisher to use.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"publisher_config": schema.StringAttribute{
				Description: "Publisher-specific configuration (e.g. webhook URL, email address). Typically JSON.",
				Optional:    true,
			},
			"schedule_cron": schema.StringAttribute{
				Description: "Cron expression for scheduled notifications. Only applicable when trigger_type is 'SCHEDULE'.",
				Optional:    true,
			},
			"schedule_skip_unchanged": schema.BoolAttribute{
				Description: "Whether to skip sending scheduled notifications when there are no changes. Only applicable when trigger_type is 'SCHEDULE'. Defaults to false.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
		},
	}
}

func (r *notificationRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan notificationRuleResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisherUUID, diag := TryParseUUID(plan.PublisherID, LifecycleCreate, path.Root("publisher_id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	triggerType := dtrack.NotificationRuleTriggerType(plan.TriggerType.ValueString())

	tflog.Debug(ctx, "Creating Notification Rule", map[string]any{
		"name":         plan.Name.ValueString(),
		"scope":        plan.Scope.ValueString(),
		"trigger_type": plan.TriggerType.ValueString(),
		"publisher_id": publisherUUID.String(),
	})

	var ruleRes dtrack.NotificationRule
	var err error

	if triggerType == dtrack.NotificationRuleTriggerTypeSchedule {
		ruleRes, err = r.client.Notification.CreateScheduledRule(ctx, dtrack.CreateScheduledNotificationRuleRequest{
			Name:             plan.Name.ValueString(),
			Scope:            dtrack.NotificationRuleScope(plan.Scope.ValueString()),
			NotificatonLevel: dtrack.NotificationRuleLevel(plan.NotificationLevel.ValueString()),
			Publisher: dtrack.NotificationPublisher{
				UUID: publisherUUID,
			},
		})
	} else {
		ruleRes, err = r.client.Notification.CreateRule(ctx, dtrack.NotificationRule{
			Name:        plan.Name.ValueString(),
			Scope:       dtrack.NotificationRuleScope(plan.Scope.ValueString()),
			TriggerType: triggerType,
			Publisher: dtrack.NotificationPublisher{
				UUID: publisherUUID,
			},
		})
	}
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating notification rule",
			"Error from: "+err.Error(),
		)
		return
	}

	// Update the rule with all the remaining fields that Create doesn't support.
	updateReq := ruleRes
	updateReq.Name = plan.Name.ValueString()
	updateReq.Enabled = plan.Enabled.ValueBool()
	updateReq.NotifyChildren = plan.NotifyChildren.ValueBool()
	updateReq.LogSuccessfulPublish = plan.LogSuccessfulPublish.ValueBool()
	if !plan.NotificationLevel.IsNull() && !plan.NotificationLevel.IsUnknown() {
		updateReq.NotificationLevel = dtrack.NotificationRuleLevel(plan.NotificationLevel.ValueString())
	}
	if !plan.Message.IsNull() && !plan.Message.IsUnknown() {
		updateReq.Message = plan.Message.ValueString()
	}
	if !plan.PublisherConfig.IsNull() && !plan.PublisherConfig.IsUnknown() {
		updateReq.PublisherConfig = plan.PublisherConfig.ValueString()
	}
	if !plan.ScheduleCron.IsNull() && !plan.ScheduleCron.IsUnknown() {
		updateReq.ScheduleCron = plan.ScheduleCron.ValueString()
	}
	updateReq.ScheduleSkipUnchanged = plan.ScheduleSkipUnchanged.ValueBool()

	notifyOnValues := r.getNotifyOn(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	updateReq.NotifyOn = notifyOnValues

	ruleRes, err = r.client.Notification.UpdateRule(ctx, updateReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating notification rule after creation",
			"Error from: "+err.Error(),
		)
		return
	}

	r.mapToState(ctx, &plan, ruleRes, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Created Notification Rule", map[string]any{
		"id":   plan.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
}

func (r *notificationRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state notificationRuleResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ruleID, diag := TryParseUUID(state.ID, LifecycleRead, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	tflog.Debug(ctx, "Reading Notification Rule", map[string]any{
		"id": ruleID.String(),
	})

	rule, err := r.findRule(ctx, ruleID)
	if err != nil {
		resp.State.RemoveResource(ctx)
		return
	}

	r.mapToState(ctx, &state, *rule, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Read Notification Rule", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

func (r *notificationRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan notificationRuleResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ruleID, diag := TryParseUUID(plan.ID, LifecycleUpdate, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	publisherUUID, diag := TryParseUUID(plan.PublisherID, LifecycleUpdate, path.Root("publisher_id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	notifyOnValues := r.getNotifyOn(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	updateReq := dtrack.NotificationRule{
		UUID:                 ruleID,
		Name:                 plan.Name.ValueString(),
		Enabled:              plan.Enabled.ValueBool(),
		NotifyChildren:       plan.NotifyChildren.ValueBool(),
		LogSuccessfulPublish: plan.LogSuccessfulPublish.ValueBool(),
		Scope:                dtrack.NotificationRuleScope(plan.Scope.ValueString()),
		TriggerType:          dtrack.NotificationRuleTriggerType(plan.TriggerType.ValueString()),
		NotifyOn:             notifyOnValues,
		Publisher: dtrack.NotificationPublisher{
			UUID: publisherUUID,
		},
		ScheduleSkipUnchanged: plan.ScheduleSkipUnchanged.ValueBool(),
	}
	if !plan.NotificationLevel.IsNull() && !plan.NotificationLevel.IsUnknown() {
		updateReq.NotificationLevel = dtrack.NotificationRuleLevel(plan.NotificationLevel.ValueString())
	}
	if !plan.Message.IsNull() && !plan.Message.IsUnknown() {
		updateReq.Message = plan.Message.ValueString()
	}
	if !plan.PublisherConfig.IsNull() && !plan.PublisherConfig.IsUnknown() {
		updateReq.PublisherConfig = plan.PublisherConfig.ValueString()
	}
	if !plan.ScheduleCron.IsNull() && !plan.ScheduleCron.IsUnknown() {
		updateReq.ScheduleCron = plan.ScheduleCron.ValueString()
	}

	tflog.Debug(ctx, "Updating Notification Rule", map[string]any{
		"id":   ruleID.String(),
		"name": updateReq.Name,
	})

	ruleRes, err := r.client.Notification.UpdateRule(ctx, updateReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to update notification rule",
			"Error from: "+err.Error(),
		)
		return
	}

	r.mapToState(ctx, &plan, ruleRes, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Updated Notification Rule", map[string]any{
		"id":   plan.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
}

func (r *notificationRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state notificationRuleResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ruleID, diag := TryParseUUID(state.ID, LifecycleDelete, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	tflog.Debug(ctx, "Deleting Notification Rule", map[string]any{
		"id":   ruleID.String(),
		"name": state.Name.ValueString(),
	})

	// Remove all associations before deleting to avoid server-side errors.
	rule, findErr := r.findRule(ctx, ruleID)
	if findErr == nil {
		for _, project := range rule.Projects {
			_, err := r.client.Notification.RemoveProjectFromRule(ctx, ruleID, project.UUID)
			if err != nil {
				resp.Diagnostics.AddError(
					"Unable to remove project from notification rule before deletion",
					"Error from: "+err.Error(),
				)
				return
			}
		}
		for _, team := range rule.Teams {
			_, err := r.client.Notification.RemoveTeamFromRule(ctx, ruleID, team.UUID)
			if err != nil {
				resp.Diagnostics.AddError(
					"Unable to remove team from notification rule before deletion",
					"Error from: "+err.Error(),
				)
				return
			}
		}
		for _, tag := range rule.Tags {
			err := r.client.Tag.UntagNotificationRules(ctx, tag.Name, []uuid.UUID{ruleID})
			if err != nil {
				resp.Diagnostics.AddError(
					"Unable to remove tag from notification rule before deletion",
					"Error from: "+err.Error(),
				)
				return
			}
		}
	}

	err := r.client.Notification.DeleteRule(ctx, dtrack.NotificationRule{UUID: ruleID})
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to delete notification rule",
			"Error from: "+err.Error(),
		)
		return
	}
	tflog.Debug(ctx, "Deleted Notification Rule", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

func (*notificationRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Importing Notification Rule", map[string]any{
		"id": req.ID,
	})
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Imported Notification Rule", map[string]any{
		"id": req.ID,
	})
}

func (r *notificationRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfoData, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfoData.client
	r.semver = clientInfoData.semver
}

func (r *notificationRuleResource) findRule(ctx context.Context, ruleID uuid.UUID) (*dtrack.NotificationRule, error) {
	allRules, err := dtrack.FetchAll(func(po dtrack.PageOptions) (dtrack.Page[dtrack.NotificationRule], error) {
		return r.client.Notification.GetAllRules(ctx, po, dtrack.SortOptions{}, dtrack.GetAllRulesFilterOptions{})
	})
	if err != nil {
		return nil, err
	}
	return Find(allRules, func(rule dtrack.NotificationRule) bool {
		return rule.UUID == ruleID
	})
}

func (*notificationRuleResource) getNotifyOn(ctx context.Context, plan notificationRuleResourceModel, diagnostics *diag.Diagnostics) []dtrack.NotificationRuleNotifyOn {
	if plan.NotifyOn.IsNull() || plan.NotifyOn.IsUnknown() {
		return nil
	}
	var notifyOnStrings []string
	diags := plan.NotifyOn.ElementsAs(ctx, &notifyOnStrings, false)
	diagnostics.Append(diags...)
	if diagnostics.HasError() {
		return nil
	}
	return Map(notifyOnStrings, func(s string) dtrack.NotificationRuleNotifyOn {
		return dtrack.NotificationRuleNotifyOn(s)
	})
}

func (*notificationRuleResource) mapToState(ctx context.Context, state *notificationRuleResourceModel, rule dtrack.NotificationRule, diagnostics *diag.Diagnostics) {
	state.ID = types.StringValue(rule.UUID.String())
	state.Name = types.StringValue(rule.Name)
	state.Enabled = types.BoolValue(rule.Enabled)
	state.NotifyChildren = types.BoolValue(rule.NotifyChildren)
	state.LogSuccessfulPublish = types.BoolValue(rule.LogSuccessfulPublish)
	state.Scope = types.StringValue(string(rule.Scope))
	state.TriggerType = types.StringValue(string(rule.TriggerType))
	state.PublisherID = types.StringValue(rule.Publisher.UUID.String())
	state.ScheduleSkipUnchanged = types.BoolValue(rule.ScheduleSkipUnchanged)

	if rule.NotificationLevel != "" {
		state.NotificationLevel = types.StringValue(string(rule.NotificationLevel))
	} else {
		state.NotificationLevel = types.StringNull()
	}

	if rule.Message != "" {
		state.Message = types.StringValue(rule.Message)
	} else if !state.Message.IsNull() {
		state.Message = types.StringNull()
	}

	if rule.PublisherConfig != "" {
		state.PublisherConfig = types.StringValue(rule.PublisherConfig)
	} else if !state.PublisherConfig.IsNull() {
		state.PublisherConfig = types.StringNull()
	}

	if rule.ScheduleCron != "" {
		state.ScheduleCron = types.StringValue(rule.ScheduleCron)
	} else if !state.ScheduleCron.IsNull() {
		state.ScheduleCron = types.StringNull()
	}

	if len(rule.NotifyOn) > 0 {
		notifyOnStrings := Map(rule.NotifyOn, func(n dtrack.NotificationRuleNotifyOn) string {
			return string(n)
		})
		notifyOnSet, diags := types.SetValueFrom(ctx, types.StringType, notifyOnStrings)
		diagnostics.Append(diags...)
		state.NotifyOn = notifyOnSet
	} else {
		state.NotifyOn = types.SetNull(types.StringType)
	}
}
